name: ECR 업로드
on:
  push:
    branches:
      - main  


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4



    # AWS 자격 증명을 설정합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-actions
        aws-region: ap-northeast-2  
    
    # Amazon ECR(Elastic Container Registry)에 로그인합니다.
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'
    
    # Docker 이미지를 빌드하고 ECR에 푸시합니다.
    # ECR_REGISTRY: Amazon ECR 레지스트리 URL.
    # ECR_REPOSITORY: ECR 내 저장소 이름.
    # IMAGE_TAG: GitHub 커밋 SHA를 이미지 태그로 사용하여 이미지의 버전을 관리합니다. 
    # 이 이미지가 빌드되고, 지정된 ECR 리포지토리에 푸시됩니다.
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-northeast-2.amazonaws.com # 수정 []포함 내용 삭제후 생성된  registry 입력
	      ECR_REPOSITORY: test
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
